# Generated by Django 3.2.12 on 2022-04-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Products', 'verbose_name_plural': 'categories'},
        ),
    ]
